python:
  - "2.7"
sudo: required
dist: trusty
addons:
  apt:
    packages:
    - python-yaml
    - cmake
    - bison
    - flex
    - git
    - autoconf
    - automake
    - libtool
    - antlr
    - wget
    - fakeroot
cache: ccache
install:
  - sudo update-ca-certificates -f
  - wget -q "http://dl.google.com/android/repository/android-ndk-r11c-linux-x86_64.zip" -O /tmp/ndk.zip
  - ( cd $HOME; unzip -q /tmp/ndk.zip; mv android-ndk-* .ndk )
  - rvm use 1.9.3-p125 --install
before_script:
  - echo -e 'G_MAINTAINER="travis"\nG_NDKPATH="$HOME/.ndk"' > config.sh
  - export PYTHONPATH="/usr/lib/python2.7/dist-packages"
script:
  - ./botbrew toolchain
  - ./botbrew makefile > Makefile
  - sed -i -E 's#(@cd ([^;]+)/gcc;)(.*)(; cat [^;]+)#\1 \3; cat \2/gcc/object/arm-linux-androideabi/armv7-a/hard/libgcc/config.log#p' Makefile
  - ln -s "$(which ccache)" "bin/arm-linux-androideabi-g++"
  - ln -s "$(which ccache)" "bin/arm-linux-androideabi-gcc"
  - ln -s "$(which ccache)" "bin/arm-linux-androideabi-gcc-4.9"
  - ln -s "$(which ccache)" "bin/arm-linux-androideabi-c++"
  - ln -s "$(which ccache)" "bin/arm-linux-androideabi-c++filt"
  - ln -s "$(which ccache)" "bin/arm-linux-androideabi-cpp"
  - make -s -k package-nmap package-ettercap package-ruby package-hydra 
notifications:
  slack:
    rooms:
      - csploit:BYr15dcnal0Dm6UZRafBqWSC#travis
      - csploit:BYr15dcnal0Dm6UZRafBqWSC#dev
